apiVersion: v1
kind: ConfigMap
metadata:
  name: campanha-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Settings__RabbitMq__HostName: "rabbitmq"
  Settings__RabbitMq__UserName: "guest"
  Settings__RabbitMq__Password: "guest"
  Settings__IdCryptographyAlphabet: "peKcMZ1lrFsDOdA2Rxj9H85Bohw6aGJNvITgQf403ntSqkXmUVWyiCLu7PzYEb"