apiVersion: apps/v1
kind: Deployment
metadata:
  name: campanha-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campanha-api
  template:
    metadata:
      labels:
        app: campanha-api
    spec:
      containers:
        - name: campanha-api
          image: campanha-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: campanha-config
            - secretRef:
                name: campanha-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10